# LGTM configuration file
# Needed to configure .NET Core extraction as it failes to do it automatically
extraction:
  csharp:
    prepare:
      packages:
        - nodejs
    index:
      dotnet:
        version: 3.1.406